---
title: "Analysis"
author: "Patrick"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(beeswarm)
library(readxl)
library(janitor)
library(stringdist)
library(fuzzyjoin)
library(geoclient)
library(getarc)
library(sf)

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
scores23 <- read_excel("PH_Inspections_data_dotgov_27JUN2023.xlsx") %>% 
  clean_names() %>% 
  filter(pha_code == "NY005")

scores24 <- read_excel("PH_UPCSInspections_Data_dotgov_19APR2024.xlsx") %>% 
  clean_names() %>% 
  filter(pha_code == "NY005")

scores25 <- read_excel("public_housing_physical_inspection_scores_08252025.xlsx") %>% 
  clean_names() %>% 
  filter(pha_code == "NY005")

test <- full_join(PH_Inspections_data_dotgov_27JUN2023, PH_UPCSInspections_Data_dotgov_19APR2024, by = c("Inspection ID"="UPCS Inspection ID")) #new data has 6 less rows, the rest is the same, keep old data
```

```{r}
nycha_scores <- scores25 %>% 
  mutate(raw_score = as.integer(str_replace_all(inspection_score, "[*abc]", "")),
         pass = if_else(raw_score >= 60, T, F),
         h_s_score = toupper(str_replace_all(inspection_score, "[*0-9]", "")),
         smoke_detectors = if_else(str_detect(inspection_score, "\\*"), "Yes", "No"),
        development_name = str_replace_all(development_name, "\\.", "")

  )

clean_23 <- scores23 %>% 
  mutate(raw_score = as.integer(str_replace_all(inspection_score, "[*abc]", "")),
         pass = if_else(raw_score >= 60, T, F),
         h_s_score = toupper(str_replace_all(inspection_score, "[*0-9]", "")),
         smoke_detectors = if_else(str_detect(inspection_score, "\\*"), "Yes", "No"),
        development_name = str_replace_all(development_name, "\\.", "")

  )

clean_23 %>% count( 
                   h_s_score
                   )

write_csv(nycha_scores, "nycha_scores.csv")
```

```{r}

nycha_bees <- beeswarm(
  raw_score ~ axis,
  data = nycha_scores %>% mutate(axis = 0),
  method = "compactswarm",
  cex = 1,
  vertical = F,
  pch = 16,
)

rownames(nycha_bees) <- NULL


nycha_scores_beeswarm <- bind_cols(nycha_bees, nycha_scores) %>% 
  select(x = y, y = x, development_name, pass, raw_score) #this is dumb but makes is a lot easier for DW to read. Switching it to horizontal by just renaming and reordering the x and y columns

write_csv(nycha_scores_beeswarm, "scores_swarm_dw.csv")

```


```{r}

#merge in PNA
pna_23 <- read_csv("NYCHA 2023 PNA Development Results 7-1-2023(in) (1).csv") %>% 
  clean_names()

pna_dev_sum <- pna_23 %>% 
  group_by(development, primary_work_type) %>% 
  summarize(need_5 = sum(x5_year_need, na.rm = T),
            need_20 = sum(x20_year_need, na.rm = T),
            ) %>%  
  arrange(development, desc(need_20)) %>% 
  ungroup() %>% 
  group_by(development) %>% 
  summarize(x_need_5 = sum(need_5, na.rm = T),
            x_need_20 = sum(need_20, na.rm = T),
            cat_1 = first(primary_work_type),
            cat_1_amt = first(need_20),
            cat_2 = nth(primary_work_type, 2),
            cat_2_amt = nth(need_20, 2),
            cat_3 = nth(primary_work_type, 3),
            cat_3_amt = nth(need_20, 3)
            )

pna_23 %>% summarize(total_5 = sum(x5_year_need, na.rm = T), total_20 = sum(x20_year_need, na.rm = T))


pna_18 <- read_excel("Master NYCHA PNA Spread Sheet DCabrera.xlsx") %>% 
  clean_names()

pna_time <- left_join(pna_dev_sum, pna_18, by = "development")

pna_time %>% count(is.na(data_as_of)) #all match!!

dev_sum_clean <- pna_time %>% 
  mutate(cap_per_unit = x_need_20/total_number_of_apartments,
         geo = geo_intersection(cross_street_1 = location_street_a,
                        cross_street_2 = location_street_b,
                        borough = borough)) %>% 
  select(development, x_need_20, total_number_of_apartments, cap_per_unit, starts_with("cat_"))

dev_sum_clean %>% write_csv("pna_table.csv")
  

```


```{r}
nycha_dev_layer <- query_layer("https://services1.arcgis.com/0mhlGDIUKwQF6tnJ/arcgis/rest/services/NYCHA_developments_public2017/FeatureServer/0") %>% 
                                 mutate(layer = "NYCHA")

pact_dev_layer <- query_layer("https://services1.arcgis.com/0mhlGDIUKwQF6tnJ/arcgis/rest/services/20200212_RADPACT_Layer/FeatureServer/1") %>% 
  mutate(layer = "PACT",
         TOTAL_UNIT = TOTAL_DU)

nycha_pact_sf <- bind_rows(nycha_dev_layer, pact_dev_layer) %>% 
  st_centroid() %>% 
  mutate(
    long = st_coordinates(geometry)[, 1],
    lat  = st_coordinates(geometry)[, 2]
  ) %>% 
  as.data.frame

join_sf <- left_join(dev_sum_clean, nycha_pact_sf, by = c("development"="DEVELOPMEN")) %>% 
  arrange(desc(cap_per_unit)) %>% 
  mutate(cap_unit_rank = row_number()) %>%
  arrange(desc(x_need_20)) %>% 
  mutate(cap_rank = row_number())

join_sf %>% select(development, x_need_20, cap_per_unit, BOROUGH, total_number_of_apartments, layer, long, lat, starts_with("cat_"), cap_rank, cap_unit_rank) %>% 
  write_csv("pna_map.csv")
  
```



```{r}

nhpd_reac <-read_excel("active_ph_pbs8_nystate.xlsx") %>% 
  clean_names()
  
nyc_nhpd <- filter(nhpd_reac, county %in% c("Kings", "Richmond", "New York", "Bronx", "Queens"))

nycha_nhpd <- filter(nyc_nhpd, manager_name %in% c("New York City Housing Authority", "NEW YORK CITY HOUSING AUTHORITY", "CORNELL PACE INC")) %>% 
#mutate for the nhpd data - will revisit
  mutate(property_name = case_when(
    property_name == "RED HOOK I EAST" ~ "red hook i (east)",
    property_name == "AMSTERDAM" & nhpd_property_id == "1072768" ~ "amsterdam addition",
    property_name == "BAYVIEW HOUSES" ~ "bay view",
    property_name == "BCH41 ST BCH CHANNEL DR" ~ "Bch.41 St/Bch. Channel Dr",
    property_name == "SEN ROBERT F WAGNER SR" ~ "Sen. Robert F. Wagner Sr.",
    property_name == "OCEAN HILL APARTMENTS" ~ "Ocean Hill apts",
    property_name == "WILLIAM REID APARTMENTS" ~ "William Reid Apts",
    property_name == "LANGSTON HUGHES APARTMENTS" ~ "Langston Hughes Apts",
    property_name == "UPACA URA SITE 5" ~ "U.P.A.C.A. Ura (Site 5)",
    property_name == "MARLBORO HOUSES" ~ "Marlboro",
    property_name == "BUSHWICK HOUSES" ~ "Bushwick",
    property_name == "160 MADISON AVENUE APARTMENTS" ~ "Rutgers",
    property_name == "FREDERICK SAMUEL PHASE XII" ~ "Frederick Samuel (city)",
    property_name == "PROSPECT PLAZA SITE I" ~ "Prospect Plaza Phase I",
    property_name == "PROSPECT PLAZA II" ~ "Prospect Plaza Phase Ii",
    property_name == "TRINITY WEST HARLEM PHASE TWO LP" ~ "Randolph South",
    T ~ property_name
  ),
  property_name = toupper(property_name))

#boulevard houses in NHPD but not hud data

```


```{r}

join1 <- left_join(nycha_scores %>% 
                     select(development_name, inspection_score, inspection_date,
                            latitude, longitude, county_name),
                   nycha_nhpd, by = c("development_name"="property_name"))

anti_join(nycha_scores, nycha_nhpd, by = c("development_name"="property_name"))

join2 <- left_join(nycha_scores)

```



```{r}

fuzzy_join <- stringdist_join(nycha_scores, nycha_nhpd,
          by = c("development_name" = "property_name"),
          mode = "left",
          max_dist = 2,
          ignore_case = T,
          distance_col = "dist") %>% 
  group_by(development_name) %>%
  filter(dist == min(dist)) %>%
  ungroup()


anti_join <- stringdist_join(nycha_nhpd, nycha_scores,
          by = c("property_name" = "development_name"),
          mode = "anti",
          max_dist = 2,
          ignore_case = T,
          distance_col = "dist") %>% 
  ungroup()

#all except hobbs ciena are additional NYCHA

```

```{r}
map_clean <- fuzzy_join %>% 
  mutate(second_score = as.integer(str_replace_all(reac_score_1, "[*abc]", "")),
         second_pass = if_else(reac_score_2 >= 60, T, F),
         second_h_s_score = toupper(str_replace_all(reac_score_1, "[*0-9]", "")),
         second_smoke_detectors = if_else(str_detect(reac_score_1, "\\*"), "Yes", "No"),
         third_score = as.integer(str_replace_all(reac_score_2, "[*abc]", "")),
         third_pass = if_else(reac_score_2 >= 60, T, F),
         third_h_s_score = toupper(str_replace_all(reac_score_2, "[*0-9]", "")),
         third_smoke_detectors = if_else(str_detect(reac_score_2, "\\*"), "Yes", "No")
  ) %>% 
  select(development_name, borough = city.x, development_acc_unit_count = total_units,
         inspection_date, raw_score, h_s_score, smoke_detectors, reac_date_2,
         second_score, second_h_s_score, second_smoke_detectors, reac_date_3,
         third_score, third_h_s_score, third_smoke_detectors,
         latitude = latitude.x, longitude=longitude.x)

map_clean %>% 
  write_csv("scores_map_dw.csv")

pna_join <- left_join(map_clean, pna_dev_sum, by = c("development_name" = "dev_name_std"))

map_clean %>% stringdist_join(pna_dev_sum,
          by = c("development_name" = "development"),
          mode = "full",
          max_dist = 3,
          ignore_case = T,
          distance_col = "dist") %>% 
  group_by(development_name) %>%
  filter(dist == min(dist))

```

```{r}

nycha_scores %>% 
  select(`Development Name` = development_name,
         `Borough` = development_city,
         `Units` = development_acc_unit_count,
         `Overall Score` = raw_score,
         `Health & Safety Scores` = h_s_score,
         `Smoke Detector Deficiencies` = smoke_detectors) %>% 
  write_csv("scores_table_dw.csv")


```



